[tool.bumpversion]
current_version = "1.0.0"
commit = true
commit_args = "--no-verify"
tag = true
tag_name = "v{new_version}"
allow_dirty = false
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<dev>dev)\\d+\\+[-_a-zA-Z0-9]+)?"
serialize = ["{major}.{minor}.{patch}"]
message = "Version updated from {current_version} to {new_version}"
